# Generated by Django 5.1.5 on 2025-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedapiresponse',
            name='last_refreshed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cachedapiresponse',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
