# Generated by Django 5.1.5 on 2025-07-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_cachedapiresponse_last_refreshed_and_more'),
    ]

    operations = [
    ]
